version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app/todos
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=medicine
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=medicine_postgres
      - PORT=8080
    depends_on:
      - pgMedicine
    links:
      - pgMedicine
  pgMedicine:
    image: postgres
    container_name: medicine_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: medicine

networks:
  default:
    driver: bridge